name: Lazy Script(Schedule New)
on:
  push:
    branches:
      - master
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '10 0,1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,21,22,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: '${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run app
        run: npm install
      - run: node src/app.js
        env:
          NODE_ENV: production
          NOT_RUN: '${{ secrets.NOT_RUN }}'
          SEVER_CHAN_KEY: '${{ secrets.SEVER_CHAN_KEY }}'
          MAILER_TRANSPORTER_OPTION: '${{ secrets.MAILER_TRANSPORTER_OPTION }}'
          JD_FRUIT_WATER_TIMES: '${{ secrets.JD_FRUIT_WATER_TIMES }}'
          JD_FRUIT_WATER_DISABLE: '${{ secrets.JD_FRUIT_WATER_DISABLE }}'
          JD_LIVE_RED_ENVELOPE_RAIN_STOP: '${{ secrets.JD_LIVE_RED_ENVELOPE_RAIN_STOP }}'
          JD_CRAZY_JOY_STOP_UPGRADE: '${{ secrets.JD_CRAZY_JOY_STOP_UPGRADE }}'
          JD_CRAZY_JOY_STOP_UPGRADE_1: '${{ secrets.JD_CRAZY_JOY_STOP_UPGRADE_1 }}'
          JD_CRAZY_JOY_STOP_UPGRADE_2: '${{ secrets.JD_CRAZY_JOY_STOP_UPGRADE_2 }}'
          JD_CRAZY_JOY_STOP_UPGRADE_3: '${{ secrets.JD_CRAZY_JOY_STOP_UPGRADE_3 }}'
          JD_CRAZY_JOY_STOP_UPGRADE_4: '${{ secrets.JD_CRAZY_JOY_STOP_UPGRADE_4 }}'
          JD_CRAZY_JOY_STOP_UPGRADE_5: '${{ secrets.JD_CRAZY_JOY_STOP_UPGRADE_5 }}'
          JD_JOY_FEED_INDEX: '${{ secrets.JD_JOY_FEED_INDEX }}'
          JD_JOY_FEED_INDEX_1: '${{ secrets.JD_JOY_FEED_INDEX_1 }}'
          JD_JOY_FEED_INDEX_2: '${{ secrets.JD_JOY_FEED_INDEX_2 }}'
          JD_JOY_FEED_INDEX_3: '${{ secrets.JD_JOY_FEED_INDEX_3 }}'
          JD_JOY_FEED_INDEX_4: '${{ secrets.JD_JOY_FEED_INDEX_4 }}'
          JD_JOY_FEED_INDEX_5: '${{ secrets.JD_JOY_FEED_INDEX_5 }}'
          JD_SIGN_IN_AT_THE_VOUCHER_CENTER_ENABLE: '${{ secrets.JD_SIGN_IN_AT_THE_VOUCHER_CENTER_ENABLE }}'
          JD_SIGN_IN_AT_THE_VOUCHER_CENTER_ENABLE_1: '${{ secrets.JD_SIGN_IN_AT_THE_VOUCHER_CENTER_ENABLE_1 }}'
          JD_SIGN_IN_AT_THE_VOUCHER_CENTER_ENABLE_2: '${{ secrets.JD_SIGN_IN_AT_THE_VOUCHER_CENTER_ENABLE_2 }}'
          JD_SIGN_IN_AT_THE_VOUCHER_CENTER_ENABLE_3: '${{ secrets.JD_SIGN_IN_AT_THE_VOUCHER_CENTER_ENABLE_3 }}'
          JD_SIGN_IN_AT_THE_VOUCHER_CENTER_ENABLE_4: '${{ secrets.JD_SIGN_IN_AT_THE_VOUCHER_CENTER_ENABLE_4 }}'
          JD_SIGN_IN_AT_THE_VOUCHER_CENTER_ENABLE_5: '${{ secrets.JD_SIGN_IN_AT_THE_VOUCHER_CENTER_ENABLE_5 }}'
          JD_COOKIE: '${{ secrets.JD_COOKIE }}'
          JD_COOKIE_1: '${{ secrets.JD_COOKIE_1 }}'
          JD_COOKIE_2: '${{ secrets.JD_COOKIE_2 }}'
          JD_COOKIE_3: '${{ secrets.JD_COOKIE_3 }}'
          JD_COOKIE_4: '${{ secrets.JD_COOKIE_4 }}'
          JD_COOKIE_5: '${{ secrets.JD_COOKIE_5 }}'
          JD_EARN_COOKIE: '${{ secrets.JD_EARN_COOKIE }}'
          JD_EARN_COOKIE_1: '${{ secrets.JD_EARN_COOKIE_1 }}'
          JD_EARN_COOKIE_2: '${{ secrets.JD_EARN_COOKIE_2 }}'
          JD_EARN_COOKIE_3: '${{ secrets.JD_EARN_COOKIE_3 }}'
          JD_EARN_COOKIE_4: '${{ secrets.JD_EARN_COOKIE_4 }}'
          JD_EARN_COOKIE_5: '${{ secrets.JD_EARN_COOKIE_5 }}'
          JD_WQ_WX_COOKIE: '${{ secrets.JD_WQ_WX_COOKIE }}'
          JD_WQ_WX_COOKIE_1: '${{ secrets.JD_WQ_WX_COOKIE_1 }}'
          JD_WQ_WX_COOKIE_2: '${{ secrets.JD_WQ_WX_COOKIE_2 }}'
          JD_WQ_WX_COOKIE_3: '${{ secrets.JD_WQ_WX_COOKIE_3 }}'
          JD_WQ_WX_COOKIE_4: '${{ secrets.JD_WQ_WX_COOKIE_4 }}'
          JD_WQ_WX_COOKIE_5: '${{ secrets.JD_WQ_WX_COOKIE_5 }}'
          JD_APPLET_PIN: '${{ secrets.JD_APPLET_PIN }}'
          JD_APPLET_PIN_1: '${{ secrets.JD_APPLET_PIN_1 }}'
          JD_APPLET_PIN_2: '${{ secrets.JD_APPLET_PIN_2 }}'
          JD_APPLET_PIN_3: '${{ secrets.JD_APPLET_PIN_3 }}'
          JD_APPLET_PIN_4: '${{ secrets.JD_APPLET_PIN_4 }}'
          JD_APPLET_PIN_5: '${{ secrets.JD_APPLET_PIN_5 }}'
          JD_EARN_SHARE_CODE: '${{ secrets.JD_EARN_SHARE_CODE }}'
          JD_EARN_SHARE_CODE_1: '${{ secrets.JD_EARN_SHARE_CODE_1 }}'
          JD_EARN_SHARE_CODE_2: '${{ secrets.JD_EARN_SHARE_CODE_2 }}'
          JD_EARN_SHARE_CODE_3: '${{ secrets.JD_EARN_SHARE_CODE_3 }}'
          JD_EARN_SHARE_CODE_4: '${{ secrets.JD_EARN_SHARE_CODE_4 }}'
          JD_EARN_SHARE_CODE_5: '${{ secrets.JD_EARN_SHARE_CODE_5 }}'
          JD_FRUIT_SHARE_CODE: '${{ secrets.JD_FRUIT_SHARE_CODE }}'
          JD_FRUIT_SHARE_CODE_1: '${{ secrets.JD_FRUIT_SHARE_CODE_1 }}'
          JD_FRUIT_SHARE_CODE_2: '${{ secrets.JD_FRUIT_SHARE_CODE_2 }}'
          JD_FRUIT_SHARE_CODE_3: '${{ secrets.JD_FRUIT_SHARE_CODE_3 }}'
          JD_FRUIT_SHARE_CODE_4: '${{ secrets.JD_FRUIT_SHARE_CODE_4 }}'
          JD_FRUIT_SHARE_CODE_5: '${{ secrets.JD_FRUIT_SHARE_CODE_5 }}'
          JD_PET_SHARE_CODE: '${{ secrets.JD_PET_SHARE_CODE }}'
          JD_PET_SHARE_CODE_1: '${{ secrets.JD_PET_SHARE_CODE_1 }}'
          JD_PET_SHARE_CODE_2: '${{ secrets.JD_PET_SHARE_CODE_2 }}'
          JD_PET_SHARE_CODE_3: '${{ secrets.JD_PET_SHARE_CODE_3 }}'
          JD_PET_SHARE_CODE_4: '${{ secrets.JD_PET_SHARE_CODE_4 }}'
          JD_PET_SHARE_CODE_5: '${{ secrets.JD_PET_SHARE_CODE_5 }}'
          JD_CASH_SHARE_CODE: '${{ secrets.JD_CASH_SHARE_CODE }}'
          JD_CASH_SHARE_CODE_1: '${{ secrets.JD_CASH_SHARE_CODE_1 }}'
          JD_CASH_SHARE_CODE_2: '${{ secrets.JD_CASH_SHARE_CODE_2 }}'
          JD_CASH_SHARE_CODE_3: '${{ secrets.JD_CASH_SHARE_CODE_3 }}'
          JD_CASH_SHARE_CODE_4: '${{ secrets.JD_CASH_SHARE_CODE_4 }}'
          JD_CASH_SHARE_CODE_5: '${{ secrets.JD_CASH_SHARE_CODE_5 }}'
          JD_BEAN_SHARE_CODE: '${{ secrets.JD_BEAN_SHARE_CODE }}'
          JD_BEAN_SHARE_CODE_1: '${{ secrets.JD_BEAN_SHARE_CODE_1 }}'
          JD_BEAN_SHARE_CODE_2: '${{ secrets.JD_BEAN_SHARE_CODE_2 }}'
          JD_BEAN_SHARE_CODE_3: '${{ secrets.JD_BEAN_SHARE_CODE_3 }}'
          JD_BEAN_SHARE_CODE_4: '${{ secrets.JD_BEAN_SHARE_CODE_4 }}'
          JD_BEAN_SHARE_CODE_5: '${{ secrets.JD_BEAN_SHARE_CODE_5 }}'
          JD_JDFACTORY_SHARE_CODE: '${{ secrets.JD_JDFACTORY_SHARE_CODE }}'
          JD_JDFACTORY_SHARE_CODE_1: '${{ secrets.JD_JDFACTORY_SHARE_CODE_1 }}'
          JD_JDFACTORY_SHARE_CODE_2: '${{ secrets.JD_JDFACTORY_SHARE_CODE_2 }}'
          JD_JDFACTORY_SHARE_CODE_3: '${{ secrets.JD_JDFACTORY_SHARE_CODE_3 }}'
          JD_JDFACTORY_SHARE_CODE_4: '${{ secrets.JD_JDFACTORY_SHARE_CODE_4 }}'
          JD_JDFACTORY_SHARE_CODE_5: '${{ secrets.JD_JDFACTORY_SHARE_CODE_5 }}'
          JD_STALL_SHARE_CODE: '${{ secrets.JD_STALL_SHARE_CODE }}'
          JD_STALL_SHARE_CODE_1: '${{ secrets.JD_STALL_SHARE_CODE_1 }}'
          JD_STALL_SHARE_CODE_2: '${{ secrets.JD_STALL_SHARE_CODE_2 }}'
          JD_STALL_SHARE_CODE_3: '${{ secrets.JD_STALL_SHARE_CODE_3 }}'
          JD_STALL_SHARE_CODE_4: '${{ secrets.JD_STALL_SHARE_CODE_4 }}'
          JD_STALL_SHARE_CODE_5: '${{ secrets.JD_STALL_SHARE_CODE_5 }}'
          JD_STALL_SS: '${{ secrets.JD_STALL_SS }}'
          JD_STALL_SS_1: '${{ secrets.JD_STALL_SS_1 }}'
          JD_STALL_SS_2: '${{ secrets.JD_STALL_SS_2 }}'
          JD_STALL_SS_3: '${{ secrets.JD_STALL_SS_3 }}'
          JD_STALL_SS_4: '${{ secrets.JD_STALL_SS_4 }}'
          JD_STALL_SS_5: '${{ secrets.JD_STALL_SS_5 }}'
          JD_STALL_CRON_SS: '${{ secrets.JD_STALL_CRON_SS }}'
          JD_STALL_CRON_SS_1: '${{ secrets.JD_STALL_CRON_SS_1 }}'
          JD_STALL_CRON_SS_2: '${{ secrets.JD_STALL_CRON_SS_2 }}'
          JD_STALL_CRON_SS_3: '${{ secrets.JD_STALL_CRON_SS_3 }}'
          JD_STALL_CRON_SS_4: '${{ secrets.JD_STALL_CRON_SS_4 }}'
          JD_STALL_CRON_SS_5: '${{ secrets.JD_STALL_CRON_SS_5 }}'
          JD_BC_POSITION_LAT: '${{ secrets.JD_BC_POSITION_LAT }}'
          JD_BC_POSITION_LAT_1: '${{ secrets.JD_BC_POSITION_LAT_1 }}'
          JD_BC_POSITION_LAT_2: '${{ secrets.JD_BC_POSITION_LAT_2 }}'
          JD_BC_POSITION_LAT_3: '${{ secrets.JD_BC_POSITION_LAT_3 }}'
          JD_BC_POSITION_LAT_4: '${{ secrets.JD_BC_POSITION_LAT_4 }}'
          JD_BC_POSITION_LAT_5: '${{ secrets.JD_BC_POSITION_LAT_5 }}'
          JD_BC_POSITION_LNG: '${{ secrets.JD_BC_POSITION_LNG }}'
          JD_BC_POSITION_LNG_1: '${{ secrets.JD_BC_POSITION_LNG_1 }}'
          JD_BC_POSITION_LNG_2: '${{ secrets.JD_BC_POSITION_LNG_2 }}'
          JD_BC_POSITION_LNG_3: '${{ secrets.JD_BC_POSITION_LNG_3 }}'
          JD_BC_POSITION_LNG_4: '${{ secrets.JD_BC_POSITION_LNG_4 }}'
          JD_BC_POSITION_LNG_5: '${{ secrets.JD_BC_POSITION_LNG_5 }}'
          JD_SSJJ_SHARE_CODE: '${{ secrets.JD_SSJJ_SHARE_CODE }}'
          JD_SSJJ_SHARE_CODE_1: '${{ secrets.JD_SSJJ_SHARE_CODE_1 }}'
          JD_SSJJ_SHARE_CODE_2: '${{ secrets.JD_SSJJ_SHARE_CODE_2 }}'
          JD_SSJJ_SHARE_CODE_3: '${{ secrets.JD_SSJJ_SHARE_CODE_3 }}'
          JD_SSJJ_SHARE_CODE_4: '${{ secrets.JD_SSJJ_SHARE_CODE_4 }}'
          JD_SSJJ_SHARE_CODE_5: '${{ secrets.JD_SSJJ_SHARE_CODE_5 }}'
          JD_SSJJ_USER_NAME: '${{ secrets.JD_SSJJ_USER_NAME }}'
          JD_SSJJ_USER_NAME_1: '${{ secrets.JD_SSJJ_USER_NAME_1 }}'
          JD_SSJJ_USER_NAME_2: '${{ secrets.JD_SSJJ_USER_NAME_2 }}'
          JD_SSJJ_USER_NAME_3: '${{ secrets.JD_SSJJ_USER_NAME_3 }}'
          JD_SSJJ_USER_NAME_4: '${{ secrets.JD_SSJJ_USER_NAME_4 }}'
          JD_SSJJ_USER_NAME_5: '${{ secrets.JD_SSJJ_USER_NAME_5 }}'
          JD_DREAMFACTORY_SHARE_CODE: '${{ secrets.JD_DREAMFACTORY_SHARE_CODE }}'
          JD_DREAMFACTORY_SHARE_CODE_1: '${{ secrets.JD_DREAMFACTORY_SHARE_CODE_1 }}'
          JD_DREAMFACTORY_SHARE_CODE_2: '${{ secrets.JD_DREAMFACTORY_SHARE_CODE_2 }}'
          JD_DREAMFACTORY_SHARE_CODE_3: '${{ secrets.JD_DREAMFACTORY_SHARE_CODE_3 }}'
          JD_DREAMFACTORY_SHARE_CODE_4: '${{ secrets.JD_DREAMFACTORY_SHARE_CODE_4 }}'
          JD_DREAMFACTORY_SHARE_CODE_5: '${{ secrets.JD_DREAMFACTORY_SHARE_CODE_5 }}'
          JD_JXCFD_SHARE_CODE: '${{ secrets.JD_JXCFD_SHARE_CODE }}'
          JD_JXCFD_SHARE_CODE_1: '${{ secrets.JD_JXCFD_SHARE_CODE_1 }}'
          JD_JXCFD_SHARE_CODE_2: '${{ secrets.JD_JXCFD_SHARE_CODE_2 }}'
          JD_JXCFD_SHARE_CODE_3: '${{ secrets.JD_JXCFD_SHARE_CODE_3 }}'
          JD_JXCFD_SHARE_CODE_4: '${{ secrets.JD_JXCFD_SHARE_CODE_4 }}'
          JD_JXCFD_SHARE_CODE_5: '${{ secrets.JD_JXCFD_SHARE_CODE_5 }}'
          JD_NIAN_SHARE_CODE: '${{ secrets.JD_NIAN_SHARE_CODE }}'
          JD_NIAN_SHARE_CODE_1: '${{ secrets.JD_NIAN_SHARE_CODE_1 }}'
          JD_NIAN_SHARE_CODE_2: '${{ secrets.JD_NIAN_SHARE_CODE_2 }}'
          JD_NIAN_SHARE_CODE_3: '${{ secrets.JD_NIAN_SHARE_CODE_3 }}'
          JD_NIAN_SHARE_CODE_4: '${{ secrets.JD_NIAN_SHARE_CODE_4 }}'
          JD_NIAN_SHARE_CODE_5: '${{ secrets.JD_NIAN_SHARE_CODE_5 }}'
          JD_BRANDCITY_SHARE_CODE: '${{ secrets.JD_BRANDCITY_SHARE_CODE }}'
          JD_BRANDCITY_SHARE_CODE_1: '${{ secrets.JD_BRANDCITY_SHARE_CODE_1 }}'
          JD_BRANDCITY_SHARE_CODE_2: '${{ secrets.JD_BRANDCITY_SHARE_CODE_2 }}'
          JD_BRANDCITY_SHARE_CODE_3: '${{ secrets.JD_BRANDCITY_SHARE_CODE_3 }}'
          JD_BRANDCITY_SHARE_CODE_4: '${{ secrets.JD_BRANDCITY_SHARE_CODE_4 }}'
          JD_BRANDCITY_SHARE_CODE_5: '${{ secrets.JD_BRANDCITY_SHARE_CODE_5 }}'
          JD_GLOBALCHALLENGE_SHARE_CODE: '${{ secrets.JD_GLOBALCHALLENGE_SHARE_CODE }}'
          JD_GLOBALCHALLENGE_SHARE_CODE_1: '${{ secrets.JD_GLOBALCHALLENGE_SHARE_CODE_1 }}'
          JD_GLOBALCHALLENGE_SHARE_CODE_2: '${{ secrets.JD_GLOBALCHALLENGE_SHARE_CODE_2 }}'
          JD_GLOBALCHALLENGE_SHARE_CODE_3: '${{ secrets.JD_GLOBALCHALLENGE_SHARE_CODE_3 }}'
          JD_GLOBALCHALLENGE_SHARE_CODE_4: '${{ secrets.JD_GLOBALCHALLENGE_SHARE_CODE_4 }}'
          JD_GLOBALCHALLENGE_SHARE_CODE_5: '${{ secrets.JD_GLOBALCHALLENGE_SHARE_CODE_5 }}'
          JD_SPRINGREWARD_SHARE_CODE: '${{ secrets.JD_SPRINGREWARD_SHARE_CODE }}'
          JD_SPRINGREWARD_SHARE_CODE_1: '${{ secrets.JD_SPRINGREWARD_SHARE_CODE_1 }}'
          JD_SPRINGREWARD_SHARE_CODE_2: '${{ secrets.JD_SPRINGREWARD_SHARE_CODE_2 }}'
          JD_SPRINGREWARD_SHARE_CODE_3: '${{ secrets.JD_SPRINGREWARD_SHARE_CODE_3 }}'
          JD_SPRINGREWARD_SHARE_CODE_4: '${{ secrets.JD_SPRINGREWARD_SHARE_CODE_4 }}'
          JD_SPRINGREWARD_SHARE_CODE_5: '${{ secrets.JD_SPRINGREWARD_SHARE_CODE_5 }}'
          JD_XIEMI_SHARE_CODE: '${{ secrets.JD_XIEMI_SHARE_CODE }}'
          JD_XIEMI_SHARE_CODE_1: '${{ secrets.JD_XIEMI_SHARE_CODE_1 }}'
          JD_XIEMI_SHARE_CODE_2: '${{ secrets.JD_XIEMI_SHARE_CODE_2 }}'
          JD_XIEMI_SHARE_CODE_3: '${{ secrets.JD_XIEMI_SHARE_CODE_3 }}'
          JD_XIEMI_SHARE_CODE_4: '${{ secrets.JD_XIEMI_SHARE_CODE_4 }}'
          JD_XIEMI_SHARE_CODE_5: '${{ secrets.JD_XIEMI_SHARE_CODE_5 }}'
          JD_LITESIGN_SHARE_CODE: '${{ secrets.JD_LITESIGN_SHARE_CODE }}'
          JD_LITESIGN_SHARE_CODE_1: '${{ secrets.JD_LITESIGN_SHARE_CODE_1 }}'
          JD_LITESIGN_SHARE_CODE_2: '${{ secrets.JD_LITESIGN_SHARE_CODE_2 }}'
          JD_LITESIGN_SHARE_CODE_3: '${{ secrets.JD_LITESIGN_SHARE_CODE_3 }}'
          JD_LITESIGN_SHARE_CODE_4: '${{ secrets.JD_LITESIGN_SHARE_CODE_4 }}'
          JD_LITESIGN_SHARE_CODE_5: '${{ secrets.JD_LITESIGN_SHARE_CODE_5 }}'
          JD_JXFARM_SHARE_CODE: '${{ secrets.JD_JXFARM_SHARE_CODE }}'
          JD_JXFARM_SHARE_CODE_1: '${{ secrets.JD_JXFARM_SHARE_CODE_1 }}'
          JD_JXFARM_SHARE_CODE_2: '${{ secrets.JD_JXFARM_SHARE_CODE_2 }}'
          JD_JXFARM_SHARE_CODE_3: '${{ secrets.JD_JXFARM_SHARE_CODE_3 }}'
          JD_JXFARM_SHARE_CODE_4: '${{ secrets.JD_JXFARM_SHARE_CODE_4 }}'
          JD_JXFARM_SHARE_CODE_5: '${{ secrets.JD_JXFARM_SHARE_CODE_5 }}'
          JD_ZOO_SHARE_CODE: '${{ secrets.JD_ZOO_SHARE_CODE }}'
          JD_ZOO_SHARE_CODE_1: '${{ secrets.JD_ZOO_SHARE_CODE_1 }}'
          JD_ZOO_SHARE_CODE_2: '${{ secrets.JD_ZOO_SHARE_CODE_2 }}'
          JD_ZOO_SHARE_CODE_3: '${{ secrets.JD_ZOO_SHARE_CODE_3 }}'
          JD_ZOO_SHARE_CODE_4: '${{ secrets.JD_ZOO_SHARE_CODE_4 }}'
          JD_ZOO_SHARE_CODE_5: '${{ secrets.JD_ZOO_SHARE_CODE_5 }}'
          JD_JXCFD_GROUP_SHARE_CODE: '${{ secrets.JD_JXCFD_GROUP_SHARE_CODE }}'
          JD_DREAMFACTORY_TUAN_ID: '${{ secrets.JD_DREAMFACTORY_TUAN_ID }}'
          JD_DREAMFACTORY_TUAN_ACTIVE_ID: '${{ secrets.JD_DREAMFACTORY_TUAN_ACTIVE_ID }}'
