name: Lazy Script(Schedule New)
on:
  schedule:
    - cron: '10 0,1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,21,22,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: '${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(''**/package.json'') }}'
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run app
        run: npm install
      - run: node src/app.js
        env:
          NODE_ENV: production
          ACTION_ENV: '${{ secrets.ACTION_ENV }}'
          JD_COOKIE: '${{ secrets.JD_COOKIE }}'
          JD_COOKIE_1: '${{ secrets.JD_COOKIE_1 }}'
          JD_COOKIE_2: '${{ secrets.JD_COOKIE_2 }}'
          JD_COOKIE_3: '${{ secrets.JD_COOKIE_3 }}'
          JD_COOKIE_4: '${{ secrets.JD_COOKIE_4 }}'
          JD_COOKIE_5: '${{ secrets.JD_COOKIE_5 }}'
          JD_COOKIE_LIMIT: '${{ secrets.JD_COOKIE_LIMIT }}'
          SEVER_CHAN_KEY: '${{ secrets.SEVER_CHAN_KEY }}'
          MAILER_TRANSPORTER_OPTION: '${{ secrets.MAILER_TRANSPORTER_OPTION }}'
          JD_COOKIE_CONFIG: '${{ secrets.JD_COOKIE_CONFIG }}'
