name: Lazy Script(Test)
on:
  push:
    branches:
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: '${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run test
        run: npm install
      - run: node src/test.js
        env:
          NODE_ENV: production
          ACTION_ENV: '${{ secrets.ACTION_ENV }}'
          NOT_RUN: '${{ secrets.NOT_RUN }}'
          SEVER_CHAN_KEY: '${{ secrets.SEVER_CHAN_KEY }}'
          MAILER_TRANSPORTER_OPTION: '${{ secrets.MAILER_TRANSPORTER_OPTION }}'
          JD_FRUIT_WATER_DISABLE: '${{ secrets.JD_FRUIT_WATER_DISABLE }}'
          JD_PET_FEED_DISABLE: '${{ secrets.JD_PET_FEED_DISABLE }}'
          JD_LIVE_RED_ENVELOPE_RAIN_STOP: '${{ secrets.JD_LIVE_RED_ENVELOPE_RAIN_STOP }}'
          JD_COOKIE_CONFIG: '${{ secrets.JD_COOKIE_CONFIG }}'
          JD_FRUIT_DO_DEFAULT_SHARE_LAST: '${{ secrets.JD_FRUIT_DO_DEFAULT_SHARE_LAST }}'
          JD_JOY_FEED_INDEX: '${{ secrets.JD_JOY_FEED_INDEX }}'
          JD_JOY_FEED_INDEX_1: '${{ secrets.JD_JOY_FEED_INDEX_1 }}'
          JD_JOY_FEED_INDEX_2: '${{ secrets.JD_JOY_FEED_INDEX_2 }}'
          JD_JOY_FEED_INDEX_3: '${{ secrets.JD_JOY_FEED_INDEX_3 }}'
          JD_JOY_FEED_INDEX_4: '${{ secrets.JD_JOY_FEED_INDEX_4 }}'
          JD_JOY_FEED_INDEX_5: '${{ secrets.JD_JOY_FEED_INDEX_5 }}'
          JD_COOKIE: '${{ secrets.JD_COOKIE }}'
          JD_COOKIE_1: '${{ secrets.JD_COOKIE_1 }}'
          JD_COOKIE_2: '${{ secrets.JD_COOKIE_2 }}'
          JD_COOKIE_3: '${{ secrets.JD_COOKIE_3 }}'
          JD_COOKIE_4: '${{ secrets.JD_COOKIE_4 }}'
          JD_COOKIE_5: '${{ secrets.JD_COOKIE_5 }}'
          JD_EARN_COOKIE: '${{ secrets.JD_EARN_COOKIE }}'
          JD_EARN_COOKIE_1: '${{ secrets.JD_EARN_COOKIE_1 }}'
          JD_EARN_COOKIE_2: '${{ secrets.JD_EARN_COOKIE_2 }}'
          JD_EARN_COOKIE_3: '${{ secrets.JD_EARN_COOKIE_3 }}'
          JD_EARN_COOKIE_4: '${{ secrets.JD_EARN_COOKIE_4 }}'
          JD_EARN_COOKIE_5: '${{ secrets.JD_EARN_COOKIE_5 }}'
          JD_APPLET_PIN: '${{ secrets.JD_APPLET_PIN }}'
          JD_APPLET_PIN_1: '${{ secrets.JD_APPLET_PIN_1 }}'
          JD_APPLET_PIN_2: '${{ secrets.JD_APPLET_PIN_2 }}'
          JD_APPLET_PIN_3: '${{ secrets.JD_APPLET_PIN_3 }}'
          JD_APPLET_PIN_4: '${{ secrets.JD_APPLET_PIN_4 }}'
          JD_APPLET_PIN_5: '${{ secrets.JD_APPLET_PIN_5 }}'
          JD_EARN_SHARE_CODE: '${{ secrets.JD_EARN_SHARE_CODE }}'
          JD_EARN_SHARE_CODE_1: '${{ secrets.JD_EARN_SHARE_CODE_1 }}'
          JD_EARN_SHARE_CODE_2: '${{ secrets.JD_EARN_SHARE_CODE_2 }}'
          JD_EARN_SHARE_CODE_3: '${{ secrets.JD_EARN_SHARE_CODE_3 }}'
          JD_EARN_SHARE_CODE_4: '${{ secrets.JD_EARN_SHARE_CODE_4 }}'
          JD_EARN_SHARE_CODE_5: '${{ secrets.JD_EARN_SHARE_CODE_5 }}'
          JD_FRUIT_SHARE_CODE: '${{ secrets.JD_FRUIT_SHARE_CODE }}'
          JD_FRUIT_SHARE_CODE_1: '${{ secrets.JD_FRUIT_SHARE_CODE_1 }}'
          JD_FRUIT_SHARE_CODE_2: '${{ secrets.JD_FRUIT_SHARE_CODE_2 }}'
          JD_FRUIT_SHARE_CODE_3: '${{ secrets.JD_FRUIT_SHARE_CODE_3 }}'
          JD_FRUIT_SHARE_CODE_4: '${{ secrets.JD_FRUIT_SHARE_CODE_4 }}'
          JD_FRUIT_SHARE_CODE_5: '${{ secrets.JD_FRUIT_SHARE_CODE_5 }}'
          JD_PET_SHARE_CODE: '${{ secrets.JD_PET_SHARE_CODE }}'
          JD_PET_SHARE_CODE_1: '${{ secrets.JD_PET_SHARE_CODE_1 }}'
          JD_PET_SHARE_CODE_2: '${{ secrets.JD_PET_SHARE_CODE_2 }}'
          JD_PET_SHARE_CODE_3: '${{ secrets.JD_PET_SHARE_CODE_3 }}'
          JD_PET_SHARE_CODE_4: '${{ secrets.JD_PET_SHARE_CODE_4 }}'
          JD_PET_SHARE_CODE_5: '${{ secrets.JD_PET_SHARE_CODE_5 }}'
          JD_CASH_SHARE_CODE: '${{ secrets.JD_CASH_SHARE_CODE }}'
          JD_CASH_SHARE_CODE_1: '${{ secrets.JD_CASH_SHARE_CODE_1 }}'
          JD_CASH_SHARE_CODE_2: '${{ secrets.JD_CASH_SHARE_CODE_2 }}'
          JD_CASH_SHARE_CODE_3: '${{ secrets.JD_CASH_SHARE_CODE_3 }}'
          JD_CASH_SHARE_CODE_4: '${{ secrets.JD_CASH_SHARE_CODE_4 }}'
          JD_CASH_SHARE_CODE_5: '${{ secrets.JD_CASH_SHARE_CODE_5 }}'
          JD_BEAN_SHARE_CODE: '${{ secrets.JD_BEAN_SHARE_CODE }}'
          JD_BEAN_SHARE_CODE_1: '${{ secrets.JD_BEAN_SHARE_CODE_1 }}'
          JD_BEAN_SHARE_CODE_2: '${{ secrets.JD_BEAN_SHARE_CODE_2 }}'
          JD_BEAN_SHARE_CODE_3: '${{ secrets.JD_BEAN_SHARE_CODE_3 }}'
          JD_BEAN_SHARE_CODE_4: '${{ secrets.JD_BEAN_SHARE_CODE_4 }}'
          JD_BEAN_SHARE_CODE_5: '${{ secrets.JD_BEAN_SHARE_CODE_5 }}'
          JD_FACTORY_SHARE_CODE: '${{ secrets.JD_FACTORY_SHARE_CODE }}'
          JD_FACTORY_SHARE_CODE_1: '${{ secrets.JD_FACTORY_SHARE_CODE_1 }}'
          JD_FACTORY_SHARE_CODE_2: '${{ secrets.JD_FACTORY_SHARE_CODE_2 }}'
          JD_FACTORY_SHARE_CODE_3: '${{ secrets.JD_FACTORY_SHARE_CODE_3 }}'
          JD_FACTORY_SHARE_CODE_4: '${{ secrets.JD_FACTORY_SHARE_CODE_4 }}'
          JD_FACTORY_SHARE_CODE_5: '${{ secrets.JD_FACTORY_SHARE_CODE_5 }}'
          JD_DREAMFACTORY_SHARE_CODE: '${{ secrets.JD_DREAMFACTORY_SHARE_CODE }}'
          JD_DREAMFACTORY_SHARE_CODE_1: '${{ secrets.JD_DREAMFACTORY_SHARE_CODE_1 }}'
          JD_DREAMFACTORY_SHARE_CODE_2: '${{ secrets.JD_DREAMFACTORY_SHARE_CODE_2 }}'
          JD_DREAMFACTORY_SHARE_CODE_3: '${{ secrets.JD_DREAMFACTORY_SHARE_CODE_3 }}'
          JD_DREAMFACTORY_SHARE_CODE_4: '${{ secrets.JD_DREAMFACTORY_SHARE_CODE_4 }}'
          JD_DREAMFACTORY_SHARE_CODE_5: '${{ secrets.JD_DREAMFACTORY_SHARE_CODE_5 }}'
          JD_JXCFD_SHARE_CODE: '${{ secrets.JD_JXCFD_SHARE_CODE }}'
          JD_JXCFD_SHARE_CODE_1: '${{ secrets.JD_JXCFD_SHARE_CODE_1 }}'
          JD_JXCFD_SHARE_CODE_2: '${{ secrets.JD_JXCFD_SHARE_CODE_2 }}'
          JD_JXCFD_SHARE_CODE_3: '${{ secrets.JD_JXCFD_SHARE_CODE_3 }}'
          JD_JXCFD_SHARE_CODE_4: '${{ secrets.JD_JXCFD_SHARE_CODE_4 }}'
          JD_JXCFD_SHARE_CODE_5: '${{ secrets.JD_JXCFD_SHARE_CODE_5 }}'
          JD_LITESPRINGREWARD_SHARE_CODE: '${{ secrets.JD_LITESPRINGREWARD_SHARE_CODE }}'
          JD_LITESPRINGREWARD_SHARE_CODE_1: '${{ secrets.JD_LITESPRINGREWARD_SHARE_CODE_1 }}'
          JD_LITESPRINGREWARD_SHARE_CODE_2: '${{ secrets.JD_LITESPRINGREWARD_SHARE_CODE_2 }}'
          JD_LITESPRINGREWARD_SHARE_CODE_3: '${{ secrets.JD_LITESPRINGREWARD_SHARE_CODE_3 }}'
          JD_LITESPRINGREWARD_SHARE_CODE_4: '${{ secrets.JD_LITESPRINGREWARD_SHARE_CODE_4 }}'
          JD_LITESPRINGREWARD_SHARE_CODE_5: '${{ secrets.JD_LITESPRINGREWARD_SHARE_CODE_5 }}'
          JD_LITESIGN_SHARE_CODE: '${{ secrets.JD_LITESIGN_SHARE_CODE }}'
          JD_LITESIGN_SHARE_CODE_1: '${{ secrets.JD_LITESIGN_SHARE_CODE_1 }}'
          JD_LITESIGN_SHARE_CODE_2: '${{ secrets.JD_LITESIGN_SHARE_CODE_2 }}'
          JD_LITESIGN_SHARE_CODE_3: '${{ secrets.JD_LITESIGN_SHARE_CODE_3 }}'
          JD_LITESIGN_SHARE_CODE_4: '${{ secrets.JD_LITESIGN_SHARE_CODE_4 }}'
          JD_LITESIGN_SHARE_CODE_5: '${{ secrets.JD_LITESIGN_SHARE_CODE_5 }}'
          JD_JXFARM_SHARE_CODE: '${{ secrets.JD_JXFARM_SHARE_CODE }}'
          JD_JXFARM_SHARE_CODE_1: '${{ secrets.JD_JXFARM_SHARE_CODE_1 }}'
          JD_JXFARM_SHARE_CODE_2: '${{ secrets.JD_JXFARM_SHARE_CODE_2 }}'
          JD_JXFARM_SHARE_CODE_3: '${{ secrets.JD_JXFARM_SHARE_CODE_3 }}'
          JD_JXFARM_SHARE_CODE_4: '${{ secrets.JD_JXFARM_SHARE_CODE_4 }}'
          JD_JXFARM_SHARE_CODE_5: '${{ secrets.JD_JXFARM_SHARE_CODE_5 }}'
          JD_XINRUIYEAR_SHARE_CODE: '${{ secrets.JD_XINRUIYEAR_SHARE_CODE }}'
          JD_XINRUIYEAR_SHARE_CODE_1: '${{ secrets.JD_XINRUIYEAR_SHARE_CODE_1 }}'
          JD_XINRUIYEAR_SHARE_CODE_2: '${{ secrets.JD_XINRUIYEAR_SHARE_CODE_2 }}'
          JD_XINRUIYEAR_SHARE_CODE_3: '${{ secrets.JD_XINRUIYEAR_SHARE_CODE_3 }}'
          JD_XINRUIYEAR_SHARE_CODE_4: '${{ secrets.JD_XINRUIYEAR_SHARE_CODE_4 }}'
          JD_XINRUIYEAR_SHARE_CODE_5: '${{ secrets.JD_XINRUIYEAR_SHARE_CODE_5 }}'
          JD_EARNADVERTPLUGIN_INVITEID: '${{ secrets.JD_EARNADVERTPLUGIN_INVITEID }}'
          JD_EARNADVERTPLUGIN_INVITEID_1: '${{ secrets.JD_EARNADVERTPLUGIN_INVITEID_1 }}'
          JD_EARNADVERTPLUGIN_INVITEID_2: '${{ secrets.JD_EARNADVERTPLUGIN_INVITEID_2 }}'
          JD_EARNADVERTPLUGIN_INVITEID_3: '${{ secrets.JD_EARNADVERTPLUGIN_INVITEID_3 }}'
          JD_EARNADVERTPLUGIN_INVITEID_4: '${{ secrets.JD_EARNADVERTPLUGIN_INVITEID_4 }}'
          JD_EARNADVERTPLUGIN_INVITEID_5: '${{ secrets.JD_EARNADVERTPLUGIN_INVITEID_5 }}'
          JD_JXCFD_GROUP_SHARE_CODE: '${{ secrets.JD_JXCFD_GROUP_SHARE_CODE }}'
          JD_DREAMFACTORY_TUAN_ID: '${{ secrets.JD_DREAMFACTORY_TUAN_ID }}'
          JD_DREAMFACTORY_TUAN_ACTIVE_ID: '${{ secrets.JD_DREAMFACTORY_TUAN_ACTIVE_ID }}'
